In [1]:
import pandas as pd
import numpy as np

In [2]:
review = pd.read_excel('Aish_Updated_Review_Table.xlsx')
review.head()

,revId,revRating,revDate,revText,cusId,resId
0,TS67FlVZoTd1PBGWKABJqA,5,2019-07-10 08:54:37,For a 1st time visit this place was amazing! T...,NaN,NaN
1,uPI4LkkuOntW9gS6SZw-cg,3,2019-10-08 16:46:06,"I have been here several times, mostly because...",NaN,NaN
2,64Teyh5BP_JxOYuU7C8JIQ,5,2019-06-15 13:27:43,The food is consistently great and I highly re...,NaN,NaN
3,z4GN896uCw4YWZBeL5hiYQ,5,2019-11-09 05:22:45,"4.5 stars, but I'll round up because I was ple...",NaN,NaN
4,HbsXHT7wW9etlvMHp9r67A,1,2019-10-02 16:40:14,"So I'm not too big into Yelp, but I created th...",NaN,NaN

In [5]:
type(review['cusId'][0])

numpy.float64

In [3]:
write = pd.read_excel('Write.xlsx')
write.head()

                    cusId                   resId                   revId
0  K4Z8pVw56l0TnGpnZQulXg  HbF6Jy01WCp7lJYwx_Nz9g  RAnoq4EBIpomrG8GQvXA-w
1  Eho1tGZM3H0q2aUYnDAo2Q  HbF6Jy01WCp7lJYwx_Nz9g  ll1RO8hChk2lJ8RgF9-kuQ
2  2nqAt72mmoyOhfsRxvZOKA  HbF6Jy01WCp7lJYwx_Nz9g  MbrVlv9RayGjS87vViP7Hg
3  j5xwPMVeHXxYo5s9T828kA  p2ZYMPgPjMkx-UHEqLrDtQ  hMGiyazU6kJYrIlqHf-zQQ
4  sLFnNBCoyL2sGxcTdMj6eA  p2ZYMPgPjMkx-UHEqLrDtQ  5lPSeqAPjW2a8eYdbVdddg

In [8]:
for i in range(len(review)):
    index_of_revid = write[write['revId'] == review['revId'][i]].index.tolist()
    if len(index_of_revid) == 1:
        review['cusId'][i] = write['cusId'][index_of_revid[0]]
    else:
        continue
        
        
for i in range(len(review)):
    index_of_revid = write[write['revId'] == review['revId'][i]].index.tolist()
    if len(index_of_revid) == 1:
        review['resId'][i] = write['resId'][index_of_revid[0]]
    else:
        continue

C:\Users\Aishwarya\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Aishwarya\anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Aishwarya\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

In [9]:
review.head(25)

,revId,revRating,revDate,revText,cusId,resId
0,TS67FlVZoTd1PBGWKABJqA,5,2019-07-10 08:54:37,For a 1st time visit this place was amazing! T...,NaN,NaN
1,uPI4LkkuOntW9gS6SZw-cg,3,2019-10-08 16:46:06,"I have been here several times, mostly because...",NaN,NaN
2,64Teyh5BP_JxOYuU7C8JIQ,5,2019-06-15 13:27:43,The food is consistently great and I highly re...,NaN,NaN
3,z4GN896uCw4YWZBeL5hiYQ,5,2019-11-09 05:22:45,"4.5 stars, but I'll round up because I was ple...",NaN,NaN
4,HbsXHT7wW9etlvMHp9r67A,1,2019-10-02 16:40:14,"So I'm not too big into Yelp, but I created th...",N_SIgQpg30dmpEsw3i-T-g,_14dBdmGCxnNuHBH7-vOWQ
5,h7Y3OTmaE-V-LGmB_a5NYw,4,2019-08-04 16:13:42,I liked this place and want it to do well. I w...,TFYOkpzFXFBORCmo_9wIcQ,_14dBdmGCxnNuHBH7-vOWQ
6,6B3j5wFZ0c10eFKgzbtGtQ,4,2019-05-21 17:56:57,Have been to DuPont a million times and never ...,NaN,NaN
7,8TRXTS-glxUqmwNEt8YxQw,3,2019-05-16 16:52:11,Inside: The decor on the walls of with article...,NaN,NaN
8,aK2Bda1RUev9Qp4b-0xUfA,5,2019-07-13 11:31:39,This was some of the best Mediterranean food I...,NaN,NaN
9,DB8JY9QGDPRP_iwLlhfztA,4,2018-07-15 20:28:45,"In the middle of our errands for the day, I de...",NaN,NaN
10,81IGHujlCSx9XmfXKiUFmA,4,2018-07-10 13:31:22,Stopped by for some lunch here one Monday afte...,NaN,NaN
11,41LlYjhkOTvM0pdNr7fmEw,4,2017-05-21 22:05:19,Looks like new ownership of the My Las Delicia...,NaN,NaN
12,pII3qj-i1Et60ZZA_H-LVw,5,2019-07-16 17:15:30,Beat McDonald's I've had in the DC metro area....,KW4peDzzU7czXY2egPR0Hw,_7TQaKnmtAB7IX8tKB_lyw
13,iJMtpA_Besgqk_CXhwLRyA,1,2019-10-10 06:39:51,Staff needs customer service training......too...,jVX9lR1NSyJX5eNklTt2TQ,_7TQaKnmtAB7IX8tKB_lyw
14,Vds3SN0KFzOvF7YTnk17yQ,2,2019-05-11 06:27:39,"Fries are always overcooked, and nearly crispl...",KF24V0DR9qAcqiWBn9O-Dg,_7TQaKnmtAB7IX8tKB_lyw
15,84ViuPb9gpsBeDKA4W0LbA,5,2018-11-15 06:19:13,We were in the area for lunch and decided to w...,NaN,NaN
16,nhWueBzpdlhMBFU_ZTEazQ,1,2019-11-13 20:09:03,Can WMATA executives do something about how fr...,NaN,NaN
17,cNDDvGD8GCx4H__CtQ7kWA,4,2019-01-09 01:16:55,Ok. I'm going to break down and finally review...,NaN,NaN
18,Fyen2Qgqd7Cb65el2Zs6sw,5,2019-10-24 17:10:34,This place is so good! We found it by searchin...,NaN,NaN
19,q_nGgSQiQUsf7dLJAnHAgw,1,2019-11-04 11:43:59,Capitol City Brewing was conveniently located ...,NaN,NaN
20,nBOLAYBj_RRvKnUt7qJPkw,1,2019-11-02 14:41:09,A 1 star is not deserving. This bartender OSCA...,NaN,NaN
21,ur0rYS-5K2I1-Dpj3naskQ,5,2018-07-19 10:00:17,This was such a gem being from NYC I met the o...,t-CgepilG9t8fpHBdt284w,_9itFimlm02TMGGcnwoopQ
22,0XuZI4t1m51F4XKQwUys_Q,4,2019-04-01 11:54:59,This is my first time ordering here. I ordered...,bshmiA6S4iQz0_Jua_b5Zw,_9itFimlm02TMGGcnwoopQ
23,2OTl-2zPQ25fjFIfdCKFOA,1,2018-07-23 21:00:26,"Came here with my family on Monday July 23, 20...",rwH7BNPe_5eqFOo0J2NHbg,_9itFimlm02TMGGcnwoopQ
24,vIyWXCaOe-0n6GGGpg0SRA,5,2019-09-28 07:27:53,"Love this cafe with a large gelato selection, ...",NaN,NaN

In [10]:
review.to_excel('Aish_Review_Reformatted.xlsx')